//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFinding
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblFinding()
        {
            this.tblQuestions = new HashSet<tblQuestion>();
        }
    
        public int findingId { get; set; }
        public int userId { get; set; }
        public string findingName { get; set; }
        public Nullable<int> itemId { get; set; }
        public Nullable<System.DateTime> findDate { get; set; }
        public string findLocation { get; set; }
        public Nullable<int> findingStatus { get; set; }
        public string findingDescription { get; set; }
        public string findingModel { get; set; }
    
        public virtual tblUser tblUser { get; set; }
        public virtual tblItem tblItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblQuestion> tblQuestions { get; set; }
    }
}
